### ISSUE TITLE
Move endpoint storage from Ctools exportables to config entities

### ISSUE THREAD

**Issue by generalconsensus** [forumone/socrata#27]
At this point the Socrata Drupal 8 module will not correctly enable due to issues arising from the changes to the Ctools Export API. This API has moved to Drupal Core here: https://www.drupal.org/node/2164623. At this point I am finding it difficult to understand where to put the previous export payload into the new (Drupal Core API plugin?)

**Comment by PapaGrande** [comment]
Merged into 8.x-1.x.
