### ISSUE TITLE
Port curl to Guzzle

### ISSUE THREAD

**Issue by PapaGrande** [forumone/socrata#43]
Convert the code that queries a Socrata endpoint from using PHP curl to using Symfony Guzzle.  In particular, convert the execute() method of the SocrataSelectQuery class in /modules/contrib/socrata/src/SocrataSelectQuery.php.

See http://www.lohmeyer.rocks/blog/2015/10/20/0070-how-make-custom-guzzle-requests-drupal-8-modules

**Comment by PapaGrande** [comment]
Here is some example working code:

>     $client = new \GuzzleHttp\Client();
>     $siteUrl = 'https://data.seattle.gov/resource/mags-97de.json?$where=&$group=category&$select=category,sum(value)&$limit=10';
>     $res = $client->get($siteUrl, ['http_errors' => false]);
>      return($res->getBody());

**Comment by lrobeson** [comment]
I got as far as I could, but my PHP isn't good enough to handle this ticket. :-/

**Comment by PapaGrande** [comment]
#63 merged in.
