### ISSUE TITLE
Subtask: Finish socrata_views Field, Argument, Filter Plugins

### ISSUE THREAD

**Issue by PapaGrande** [forumone/socrata#44]
Subtask of #33.

Use the example plugins to create plugins for all the other Socrata datatypes.  See the D7 version for the different kinds.

**Comment by PapaGrande** [comment]
Related to #33.

**Comment by mortona42** [comment]
Related to #33

**Comment by mortona42** [comment]
Look in socrata_views.views.inc - Things like this need updating:
socrata_views_handler_field_document
socrata_views_handler_field_photo
socrata_views_handler_field_phone
socrata_views_handler_field_html

Handlers need to be written to make these fields work.

Check out socrata_views/src/Plugin/views/field/SocrataUrl.php

**Comment by PapaGrande** [comment]
See also https://api.drupal.org/api/drupal/core!modules!views!views.api.php/function/hook_views_data/8.2.x

**Comment by PapaGrande** [comment]
See https://www.lullabot.com/articles/building-views-query-plugins-for-drupal-8-part-2 for a good series on Views plugins.

**Comment by PapaGrande** [comment]
We'll likely remove [deprecated types](https://dev.socrata.com/docs/datatypes/deprecated.html), but let's do that after we've ported the plugins for the [current datatypes](https://dev.socrata.com/docs/datatypes/).

**Comment by PapaGrande** [comment]
Example of checkbox datatype: https://data.cityofchicago.org/resource/6zsd-86xi.json
