### ISSUE TITLE
Subtask: Turn of Irrelevant Views Options

### ISSUE THREAD

**Issue by PapaGrande** [forumone/socrata#47]
Turn off the options in the Views UI that aren't relevant to Socrata data such as caching.  See the D7 code for which options were suppressed there.

Subtask of #33.

**Comment by PapaGrande** [comment]
Looks like this might get done through a display_extender plugin.

**Comment by blakethomp** [comment]
@PapaGrande it looks like the 7.x version only disabled these on the Export display like you already did in #45. Does this even need to be done?

**Comment by PapaGrande** [comment]
Yes, we need to disable, at least, caching and relationships for all displays and possibly other items.

**Comment by blakethomp** [comment]
@PapaGrande this branch currently has a display extender that disables the cache settings for views using the socrata_views_query query ID. Extender is enabled on install and disabled on uninstall. 

There didn't seem to be a way to hide the relationships section even by unsetting all options, though there are no relationships available to add on a Socrata view so maybe that's okay.

Should I go ahead and create a pull request? Or hold off for now?

**Comment by PapaGrande** [comment]
> Extender is enabled on install and disabled on uninstall.
@blakestein I'd like to understand why you need to do this.  I thought plugins were auto-discovered.

I'll spend a few minutes on the relationships category.

**Comment by PapaGrande** [comment]
It looks like you can't add any relationships anyway since they aren't defined so the need for disabling the Relationships category is moot.

**Comment by PapaGrande** [comment]
@blakestein Go ahead and create a PR.

**Comment by blakethomp** [comment]
> Extender is enabled on install and disabled on uninstall.

I did this because the display extender plugins use a "no_ui" setting in the annotation.

> If it's set to TRUE, you can still use it via the API in config files.

Perhaps it should be set to false and _also_ enabled on install?

I got the idea here: http://blog.studio.gd/node/17

> Views do not discover display extender plugins with a hook info as usual, for this particular type of plugin, views has a variable in his views.settings configuration object.You need to add your plugin ID to the variable views.settings.display_extenders (that is a list).To do so, I will recommend you to implement the hook_install (as well uninstall) in the module install file. To manipulate config object you can look at my previous notes on CMI.

**Comment by PapaGrande** [comment]
Merged, but I'd like to see if we can eliminate the module install hooks.
